"use client";

import { useEffect, useRef, useState } from "react";
import CourseCoverField from "@/Components/CourseCoverField";
import CourseVideoPlayer from "@/Components/CourseVideoPlayer";
import { getCourseVideoSource } from "@/lib/course-video-source";

export default function CourseForm({ course, action, step = "details" }) {
  const [dirty, setDirty] = useState(false); const [localSaved, setLocalSaved] = useState(""); const timerRef = useRef(null); const [free, setFree] = useState(course?.isFree ?? true); const [price, setPrice] = useState(course ? course.priceMinor / 100 : 0); const [discount, setDiscount] = useState(course?.discountedPriceMinor == null ? "" : course.discountedPriceMinor / 100); const [currency, setCurrency] = useState(course?.currency || "NGN"); const [promoUrl, setPromoUrl] = useState(course?.promotionalVideoUrl || ""); const [promoOrientation, setPromoOrientation] = useState(course?.promotionalOrientation || "landscape"); const lines = (value) => Array.isArray(value) ? value.join("\n") : ""; const promo = getCourseVideoSource(promoUrl); const previewAmount = discount !== "" && Number(discount) >= 0 && Number(discount) <= Number(price) ? discount : price;
  useEffect(() => { const warn = (event) => { if (dirty) { event.preventDefault(); event.returnValue = ""; } }; const linkWarn = (event) => { const link = event.target.closest?.("a[href]"); if (dirty && link && !window.confirm("Leave this page and discard unsaved course changes?")) { event.preventDefault(); event.stopPropagation(); } }; window.addEventListener("beforeunload", warn); document.addEventListener("click", linkWarn, true); return () => { window.removeEventListener("beforeunload", warn); document.removeEventListener("click", linkWarn, true); }; }, [dirty]);
  function changed(event) { setDirty(true); setLocalSaved(""); window.clearTimeout(timerRef.current); const form = event.currentTarget; timerRef.current = window.setTimeout(() => { const values = {}; for (const [key, value] of new FormData(form)) if (typeof value === "string" && !["courseCoverCleanupKeys"].includes(key)) values[key] = value; sessionStorage.setItem(`course-draft:${course?.id || "new"}:${step}`, JSON.stringify(values)); setLocalSaved(new Date().toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" })); }, 800); }
  return <form className="admin-form course-admin-form" action={action} onChange={changed} onSubmit={() => { setDirty(false); sessionStorage.removeItem(`course-draft:${course?.id || "new"}:${step}`); }}>
    <input type="hidden" name="id" value={course?.id || ""} /><input type="hidden" name="step" value={step} />
    {step === "details" && <>
      <label>Title<input name="title" defaultValue={course?.title} required /></label><label>Slug<input name="slug" defaultValue={course?.slug} pattern="[a-z0-9]+(-[a-z0-9]+)*" required /></label>
      <label className="form-wide">Short description<textarea name="shortDescription" rows="2" defaultValue={course?.shortDescription} /></label><label className="form-wide">Full description<textarea name="description" rows="7" defaultValue={course?.description} /></label>
      <CourseCoverField course={course} /><label>Instructor<input name="instructor" defaultValue={course?.instructor} /></label><label>Category<input name="category" defaultValue={course?.category} /></label>
      <label>Difficulty<select name="difficulty" defaultValue={course?.difficulty || "All levels"}><option>Beginner</option><option>Intermediate</option><option>Advanced</option><option>All levels</option></select></label><label>Language<input name="language" defaultValue={course?.language || "English"} /></label><label>Estimated duration<input name="estimatedDuration" defaultValue={course?.estimatedDuration} placeholder="4 hours" /></label>
      <label className="form-wide">Promotional video (YouTube, Vimeo or Google Drive)<input type="url" name="promotionalVideoUrl" value={promoUrl} onChange={(event) => setPromoUrl(event.target.value)} placeholder="https://..." /></label><label>Promotional video format<select name="promotionalOrientation" value={promoOrientation} onChange={(event) => setPromoOrientation(event.target.value)}><option value="landscape">16:9 landscape</option><option value="portrait">9:16 portrait</option></select></label>
      {promoUrl && <section className="lesson-source-preview form-wide">{promo ? <CourseVideoPlayer lesson={{ id: "promo", title: "Promotional video", sourceType: promo.sourceType, embedUrl: promo.embedUrl, orientation: promoOrientation, aspectRatio: promoOrientation === "portrait" ? 9 / 16 : 16 / 9 }} admin /> : <p className="form-error">That promotional video link is not recognised.</p>}</section>}
      <label className="form-wide">Learning outcomes, one per line<textarea name="learningOutcomes" rows="5" defaultValue={lines(course?.learningOutcomes)} /></label><label className="form-wide">Requirements, one per line<textarea name="requirements" rows="4" defaultValue={lines(course?.requirements)} /></label><label className="form-wide">Target audience, one per line<textarea name="targetAudience" rows="4" defaultValue={lines(course?.targetAudience)} /></label>
      <label>SEO title<input name="seoTitle" defaultValue={course?.seoTitle} /></label><label>Open Graph image URL<input type="url" name="ogImageUrl" defaultValue={course?.ogImageUrl} /></label><label className="form-wide">SEO description<textarea name="seoDescription" rows="3" defaultValue={course?.seoDescription} /></label>
    </>}
    {step === "pricing" && <>
      <label className="check-label form-wide"><input type="checkbox" name="isFree" checked={free} onChange={(event) => setFree(event.target.checked)} />This is a free course</label>
      {!free && <><label>Regular price<input type="number" name="price" min="0.01" step="0.01" value={price} onChange={(event) => setPrice(event.target.value)} required /></label><label>Sale price<input type="number" name="discountedPrice" min="0" step="0.01" value={discount} onChange={(event) => setDiscount(event.target.value)} /></label><label>Currency<input name="currency" maxLength="3" value={currency} onChange={(event) => setCurrency(event.target.value.toUpperCase())} required /></label><label>Gateway<input value="Bachs" disabled /><small>Checkout always uses the server-side course price.</small></label><label>Sale starts<input type="datetime-local" name="saleStartsAt" defaultValue={course?.saleStartsAt?.slice(0, 16)} /></label><label>Sale ends<input type="datetime-local" name="saleEndsAt" defaultValue={course?.saleEndsAt?.slice(0, 16)} /></label></>}
      {free && <><input type="hidden" name="price" value="0" /><input type="hidden" name="currency" value={course?.currency || "NGN"} /></>}
      <label className="check-label form-wide"><input type="checkbox" name="featured" defaultChecked={course?.featured} />Feature this course publicly</label>
      <section className="course-price-preview form-wide"><small>Student price preview</small><strong>{free ? "Free" : `${currency} ${Number(previewAmount || 0).toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`}</strong>{!free && discount !== "" && <p><s>{currency} {Number(price || 0).toLocaleString(undefined, { minimumFractionDigits: 2 })}</s> during the configured sale window.</p>}<p>The checkout reads the final price from the database; the browser cannot override it.</p></section>
    </>}
    <div className="course-save-bar form-wide"><span className={dirty ? "is-dirty" : ""}>{dirty ? localSaved ? `Autosaved in this browser at ${localSaved} · save to publish changes` : "Autosaving local draft…" : course ? "All saved" : "New draft"}</span><button className="button">Save draft</button></div>
  </form>;
}
