"use client";

import Link from "next/link";
import { useEffect, useRef, useState } from "react";
import ThemeToggle from "./ThemeToggle";
import { AdminIcon, ChevronDownIcon, SocialIcon } from "./Icons";

const routes = [{ href: "/", label: "Home", icon: "home" }, { href: "/work", label: "Work", icon: "video" }, { href: "/about", label: "About", icon: "user" }, { href: "/services", label: "Services", icon: "settings" }, { href: "/contact", label: "Contact", icon: "mail" }];

export default function PublicHeader({ site, current = "/" }) {
  const [open, setOpen] = useState(false); const [closing, setClosing] = useState(false); const root = useRef(null); const timer = useRef(null);
  const initials = String(site.creatorName || "Portfolio").split(/\s+/).filter(Boolean).slice(0, 2).map((part) => part[0]).join("").toUpperCase();
  function close() { if (!open) return; setOpen(false); setClosing(true); clearTimeout(timer.current); timer.current = setTimeout(() => setClosing(false), 150); }
  useEffect(() => { const outside = (event) => { if (!root.current?.contains(event.target)) close(); }; const key = (event) => { if (event.key === "Escape") close(); }; document.addEventListener("pointerdown", outside); document.addEventListener("keydown", key); return () => { document.removeEventListener("pointerdown", outside); document.removeEventListener("keydown", key); clearTimeout(timer.current); }; });
  useEffect(() => { if (!open || window.innerWidth > 620) return; const previous = document.body.style.overflow; document.body.style.overflow = "hidden"; return () => { document.body.style.overflow = previous; }; }, [open]);
  return <header className="site-header" ref={root}><div className="identity-wrap"><Link href="/" className="identity">{site.profileImage ? <img className="profile-image" src={site.profileImage} alt="" /> : <span className="identity-mark">{initials}</span>}<span>{site.creatorName}</span></Link><button className="menu-trigger" type="button" onClick={() => { setClosing(false); setOpen((value) => !value); }} aria-expanded={open} aria-haspopup="menu" aria-label="Open site navigation"><ChevronDownIcon open={open} /></button><nav className={`t-dropdown public-menu ${open ? "is-open" : ""} ${closing ? "is-closing" : ""}`} data-origin="top-left" aria-label="Site navigation">{routes.map((route) => <span className="t-tt-wrap" key={route.href}><Link href={route.href} className={`t-tt-trigger ${current === route.href ? "is-active" : ""}`} aria-label={route.label} onClick={close}><AdminIcon name={route.icon} /><span className="menu-label">{route.label}</span></Link><span className="t-tt" role="tooltip">{route.label}</span></span>)}{site.instagramUrl && <span className="t-tt-wrap"><a className="t-tt-trigger" href={site.instagramUrl} target="_blank" rel="noreferrer" aria-label="Instagram" onClick={close}><SocialIcon name="instagram" /><span className="menu-label">Instagram</span></a><span className="t-tt" role="tooltip">Instagram</span></span>}{site.youtubeUrl && <span className="t-tt-wrap"><a className="t-tt-trigger" href={site.youtubeUrl} target="_blank" rel="noreferrer" aria-label="YouTube" onClick={close}><SocialIcon name="youtube" /><span className="menu-label">YouTube</span></a><span className="t-tt" role="tooltip">YouTube</span></span>}</nav></div><nav className="header-actions"><ThemeToggle iconOnly /><Link className="header-cta" href="/contact">{site.ctaLabel}<AdminIcon name="arrow" /></Link></nav></header>;
}
