import { randomUUID } from "node:crypto";
import { notFound } from "next/navigation";
import CourseWorkflowNav from "@/Components/CourseWorkflowNav";
import CourseLessonEditor from "@/Components/CourseLessonEditor";
import CurriculumReorder from "@/Components/CurriculumReorder";
import AdminToast from "@/Components/AdminToast";
import { getAdminCourse } from "@/lib/data/courses";
import { deleteCourseLesson, deleteCourseResource, deleteCourseSection, duplicateCourseLesson, saveCourseLesson, saveCourseSection } from "@/app/admin/actions";

function ResourceEditor({ course, lesson }) {
  return <section className="resource-admin"><h3>Private lesson PDFs</h3>{lesson.resources.map((resource) => <div key={resource.id} className="resource-row"><span><strong>{resource.title}</strong>{resource.description && <> · {resource.description}</>} · <a href={`/api/learn/resources/${resource.id}?admin=1`} target="_blank" rel="noreferrer">Preview</a></span><details><summary>Replace</summary><form action="/api/admin/course-resource" method="post" encType="multipart/form-data"><input type="hidden" name="courseId" value={course.id} /><input type="hidden" name="lessonId" value={lesson.id} /><input type="hidden" name="replacementId" value={resource.id} /><label>Title<input name="title" defaultValue={resource.title} required /></label><label>Description<input name="description" defaultValue={resource.description} /></label><label>New PDF<input type="file" name="file" accept="application/pdf,.pdf" required /></label><label className="check-label"><input type="checkbox" name="allowDownload" defaultChecked={resource.allowDownload} />Allow download</label><label className="check-label"><input type="checkbox" name="previewAllowed" defaultChecked={resource.previewAllowed} />Allow public preview</label><button className="button">Replace safely</button></form></details><form action={deleteCourseResource}><input type="hidden" name="id" value={resource.id} /><input type="hidden" name="courseId" value={course.id} /><button>Remove</button></form></div>)}<form action="/api/admin/course-resource" method="post" encType="multipart/form-data"><input type="hidden" name="courseId" value={course.id} /><input type="hidden" name="lessonId" value={lesson.id} /><label>Title<input name="title" required /></label><label>Description<input name="description" /></label><label>PDF<input type="file" name="file" accept="application/pdf,.pdf" required /></label><label className="check-label"><input type="checkbox" name="allowDownload" />Allow download</label><label className="check-label"><input type="checkbox" name="previewAllowed" />Allow public preview</label><button className="button">Upload PDF</button></form></section>;
}

export default async function CurriculumPage({ params, searchParams }) {
  const [{ id }, query] = await Promise.all([params, searchParams]); const course = await getAdminCourse(id); if (!course) notFound(); const saved = query.saved === "section" ? "Section saved." : query.saved === "lesson" ? "Lesson saved." : query.saved === "resource" ? "Resource saved." : query.saved === "duplicated" ? "Lesson duplicated as a draft." : query.saved === "deleted" ? "Curriculum item deleted." : "";
  return <><div className="admin-title"><p>COURSES</p><h1>{course.title} curriculum</h1><p className="admin-lede">Organise sections, lessons, video sources and lesson resources. Draft content stays hidden from students.</p></div><CourseWorkflowNav courseId={id} course={course} active="curriculum" /><AdminToast message={query.error || saved} kind={query.error ? "error" : "success"} /><CurriculumReorder courseId={course.id} sections={course.sections} />
    <section className="curriculum-editor">{course.sections.map((section) => <article key={section.id} className="curriculum-section"><form className="admin-form compact" action={saveCourseSection}><input type="hidden" name="id" value={section.id} /><input type="hidden" name="courseId" value={course.id} /><label>Section title<input name="title" defaultValue={section.title} required /></label><label>Description<input name="description" defaultValue={section.description} /></label><button className="button">Update section</button><button formAction={deleteCourseSection}>Delete section</button></form>
      {section.lessons.map((lesson) => <details key={lesson.id} className="lesson-editor"><summary>{lesson.title}<small>{lesson.status}{lesson.isPreview ? " · free preview" : ""}</small></summary><CourseLessonEditor course={course} section={section} sections={course.sections} lesson={lesson} lessonId={lesson.id} saveAction={saveCourseLesson} deleteAction={deleteCourseLesson} duplicateAction={duplicateCourseLesson} /><ResourceEditor course={course} lesson={lesson} /></details>)}
      <details className="lesson-editor"><summary>Add lesson to {section.title}</summary><CourseLessonEditor course={course} section={section} sections={course.sections} lessonId={randomUUID()} saveAction={saveCourseLesson} deleteAction={deleteCourseLesson} duplicateAction={duplicateCourseLesson} /></details></article>)}</section>
    <form className="admin-form compact" action={saveCourseSection}><input type="hidden" name="courseId" value={course.id} /><label>New section title<input name="title" required /></label><label>Description<input name="description" /></label><button className="button">Add section</button></form>
  </>;
}
